# Generated by Django 5.0.1 on 2024-02-16 05:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=200)),
                ('state_code', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2024, 2, 16, 11, 14, 20, 268251))),
                ('updated_date', models.DateTimeField(default=datetime.datetime(2024, 2, 16, 11, 14, 20, 268251))),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.BigIntegerField()),
                ('city', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('joining_date', models.DateField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2024, 2, 16, 11, 14, 20, 268251))),
                ('updated_date', models.DateTimeField(default=datetime.datetime(2024, 2, 16, 11, 14, 20, 268251))),
                ('is_active', models.BooleanField(default=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.statemaster')),
            ],
        ),
        migrations.CreateModel(
            name='TaskMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=250)),
                ('assign_date', models.DateField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2024, 2, 16, 11, 14, 20, 268251))),
                ('updated_date', models.DateTimeField(default=datetime.datetime(2024, 2, 16, 11, 14, 20, 268251))),
                ('is_active', models.BooleanField(default=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.statemaster')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.usermaster')),
            ],
        ),
    ]
